
<footer>CSC 174:Advanced Front-End Web Design and Development</footer>

<nav class="menu">
	<ul>
		<li><a href="index.php">Home</a></li>
		<li><a href="object_oriented_languages.php">OO Languages</a></li>
		<li><a href="philosophers.php">Philosophers</a></li>
		<li><a href="streaming_services.php">Streaming</a></li>
	</ul>
</nav>


 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
 <script src="js/menu-highlighter.js"></script>
 <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script></body>

</html>
